# Generated by Django 2.2.2 on 2019-07-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover',
            field=models.CharField(default='http://localhost/images/covers/necklace.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
