# Generated by Django 2.2.2 on 2019-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.FileField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
