# Generated by Django 2.2.2 on 2019-10-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributevalue',
            old_name='attributes',
            new_name='attribute',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='backend.Product'),
        ),
    ]
