# Generated by Django 2.2.2 on 2019-07-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Image'),
        ),
    ]
