# Generated by Django 2.2.2 on 2020-01-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='weight',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
