# Generated by Django 2.2.2 on 2019-07-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='products',
            new_name='product',
        ),
    ]
