# Generated by Django 2.2.2 on 2019-10-20 08:54

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191020_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=11, validators=[backend.validators.validate_phone_number]),
        ),
    ]
