# Generated by Django 2.2.2 on 2020-01-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_variant_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='variants', to='backend.Size'),
        ),
    ]
