# Generated by Django 2.2.2 on 2019-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190706_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover',
            field=models.CharField(max_length=100),
        ),
    ]
