# Generated by Django 2.2.2 on 2019-08-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190820_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
