# Generated by Django 2.2.2 on 2019-08-20 10:21

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190820_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=backend.models.get_filename),
        ),
    ]
