# Generated by Django 2.2.2 on 2019-10-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingbanner',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landingbanner',
            name='image',
            field=models.ImageField(upload_to='images/banners/'),
        ),
    ]
