# Generated by Django 2.2.2 on 2019-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190820_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='attributes', to='backend.Product'),
        ),
    ]
