# Generated by Django 2.2.2 on 2019-07-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190704_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='products',
        ),
    ]
