# Generated by Django 2.2.2 on 2019-10-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191004_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='attribute',
            new_name='attributes',
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
    ]
