# Generated by Django 2.2.2 on 2019-07-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='url',
            new_name='image',
        ),
    ]
