# Generated by Django 2.2.2 on 2019-10-03 08:53

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190822_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=15, validators=[backend.models.validate_phone_number]),
        ),
    ]
