# Generated by Django 2.2.2 on 2019-07-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_productattributevalue_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='products',
            field=models.ManyToManyField(related_name='attribute_values', to='backend.Product'),
        ),
    ]
