# Generated by Django 2.2.2 on 2019-07-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attribute',
        ),
    ]
