# Generated by Django 2.2.2 on 2019-10-03 10:51

import backend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191003_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=11, validators=[backend.validators.validate_phone_number]),
        ),
    ]
