# Generated by Django 2.2.2 on 2019-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190713_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='url',
            field=models.CharField(default='http://localhost', max_length=100),
            preserve_default=False,
        ),
    ]
