# Generated by Django 2.2.2 on 2019-10-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='attributes',
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='backend.AttributeValue'),
        ),
    ]
