# Generated by Django 2.2.2 on 2019-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191004_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
