# Generated by Django 2.2.2 on 2019-07-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_order_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
