# Generated by Django 2.2.2 on 2019-10-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='price',
        ),
    ]
