# Generated by Django 2.2.2 on 2019-10-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
    ]
