# Generated by Django 2.2.2 on 2019-07-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_landingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
