# Generated by Django 2.2.2 on 2019-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_productattributevalue_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='ProductAttributeValue',
            new_name='AttributeValue',
        ),
        migrations.AddField(
            model_name='category',
            name='attribites',
            field=models.ManyToManyField(related_name='categories', to='backend.Attribute'),
        ),
    ]
