# Generated by Django 2.2.2 on 2019-10-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='attribites',
            new_name='attributes',
        ),
    ]
