# Generated by Django 2.2.2 on 2019-10-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20191006_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='products',
        ),
        migrations.AddField(
            model_name='variant',
            name='products',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.Product'),
            preserve_default=False,
        ),
    ]
