# Generated by Django 2.2.2 on 2019-10-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191006_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='attribites',
            new_name='attributes',
        ),
    ]
