# Generated by Django 2.2.2 on 2019-10-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_variant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
