# Generated by Django 2.2.2 on 2019-10-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20191006_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.Variant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
