# Generated by Django 2.2.2 on 2019-10-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20191006_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='backend.Variant'),
        ),
    ]
