# Generated by Django 2.2.2 on 2019-10-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20191006_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cover',
            new_name='image',
        ),
    ]
