# Generated by Django 2.2.2 on 2019-10-10 03:34

import backend.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20191009_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='main',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='backend.Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=11, validators=[backend.validators.validate_phone_number]),
        ),
    ]
