# Generated by Django 2.2.2 on 2019-10-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20191010_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.Image'),
        ),
    ]
