# Generated by Django 2.2.2 on 2019-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_variant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='variants', to='backend.Image'),
        ),
    ]
