# Generated by Django 2.2.2 on 2019-10-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_auto_20191010_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='image',
            new_name='images',
        ),
    ]
